# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: node_js
node_js:
  - "node"
  - "7"
#   - "6" # async requires node 7+

addons:
  code_climate:
    repo_token: 03efc488f6c9db573bfcb8bbb62c37b4c44cbff16470e982ff9dd5d3eea414e3

notifications:
  email:
    on_success: change
    on_failure: change

services:
  - postgresql

before_script:
  - psql -c "CREATE USER testu WITH LOGIN CREATEDB PASSWORD 'my secret password';" -U postgres
  - export PGPASSWORD="my secret password"
  - psql -c 'create database atestdb;' -U testu -d postgres
  - psql -c 'create schema archive;' -U testu -d atestdb
  - psql -c 'create schema lookups;' -U testu -d atestdb
  - echo "{\"postgresql\":{\"host\":\"127.0.0.1\",\"port\":5432,\"username\":\"testu\",\"signatures_db\":\"atestdb\"}}" > test.config.json && chmod 0600 test.config.json

after_success:
  - npm install codeclimate-test-reporter
  - ./node_modules/.bin/tap --coverage-report=text-lcov | ./node_modules/.bin/codeclimate-test-reporter
